# Generated by Django 5.1.2 on 2024-10-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'Unico': 'Nombre de usuario no disponble! Intente con otro por favor.'}, help_text='Requerido: Ingresa un nombre de usuario.', max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece el usuario.', related_name='cuentas_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='cuentas_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres_line_1', models.CharField(blank=True, max_length=100)),
                ('addres_line_2', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile')),
                ('country', models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], default='CO', max_length=2)),
                ('state', models.CharField(choices=[('AR_BUE', 'Buenos Aires, Argentina'), ('BO_LPZ', 'La Paz, Bolivia'), ('BR_SPA', 'São Paulo, Brasil'), ('CL_STG', 'Santiago, Chile'), ('CO_ANT', 'Antioquia, Colombia'), ('CO_ATL', 'Atlántico, Colombia'), ('CO_BOL', 'Bolívar, Colombia'), ('CO_BOG', 'Cundinamarca, Colombia'), ('CO_MAG', 'Magdalena, Colombia'), ('CO_VAL', 'Valle del Cauca, Colombia'), ('CR_SJO', 'San José, Costa Rica'), ('CU_HAV', 'La Habana, Cuba'), ('DO_SDO', 'Santo Domingo, República Dominicana'), ('EC_PCH', 'Pichincha, Ecuador'), ('SV_SAL', 'San Salvador, El Salvador'), ('GT_GUA', 'Guatemala, Guatemala'), ('HN_FMZ', 'Francisco Morazán, Honduras'), ('MX_CMX', 'Ciudad de México, México'), ('NI_MNG', 'Managua, Nicaragua'), ('PA_PAC', 'Panamá, Panamá'), ('PY_ASU', 'Asunción, Paraguay'), ('PE_LIM', 'Lima, Perú'), ('UY_MVD', 'Montevideo, Uruguay'), ('VE_CCS', 'Caracas, Venezuela')], max_length=20)),
                ('city', models.CharField(choices=[('AR_BUE', 'Buenos Aires'), ('BO_LPZ', 'La Paz'), ('BR_SPA', 'São Paulo'), ('CL_STG', 'Santiago'), ('CO_ANT', 'Medellín'), ('CO_ATL', 'Barranquilla'), ('CO_BOL', 'Cartagena de Indias'), ('CO_BOG', 'Bogotá'), ('CO_MAG', 'Santa Marta'), ('CO_VAL', 'Cali'), ('CR_SJO', 'San José'), ('CU_HAV', 'La Habana'), ('DO_SDO', 'Santo Domingo'), ('EC_PCH', 'Quito'), ('SV_SAL', 'San Salvador'), ('GT_GUA', 'Guatemala'), ('HN_FMZ', 'Tegucigalpa'), ('MX_CMX', 'Ciudad de México'), ('NI_MNG', 'Managua'), ('PA_PAC', 'Ciudad de Panamá'), ('PY_ASU', 'Asunción'), ('PE_LIM', 'Lima'), ('UY_MVD', 'Montevideo'), ('VE_CCS', 'Caracas')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
