# Generated by Django 5.1.2 on 2024-10-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_addres_line_1_userprofile_address_line_1_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], default='CO', max_length=2)),
                ('state', models.CharField(choices=[('AR_BUE', 'Buenos Aires, Argentina'), ('BO_LPZ', 'La Paz, Bolivia'), ('BR_SPA', 'São Paulo, Brasil'), ('CL_STG', 'Santiago, Chile'), ('CO_ANT', 'Antioquia, Colombia'), ('CO_ATL', 'Atlántico, Colombia'), ('CO_BOL', 'Bolívar, Colombia'), ('CO_BOG', 'Cundinamarca, Colombia'), ('CO_MAG', 'Magdalena, Colombia'), ('CO_VAL', 'Valle del Cauca, Colombia'), ('CR_SJO', 'San José, Costa Rica'), ('CU_HAV', 'La Habana, Cuba'), ('DO_SDO', 'Santo Domingo, República Dominicana'), ('EC_PCH', 'Pichincha, Ecuador'), ('SV_SAL', 'San Salvador, El Salvador'), ('GT_GUA', 'Guatemala, Guatemala'), ('HN_FMZ', 'Francisco Morazán, Honduras'), ('MX_CMX', 'Ciudad de México, México'), ('NI_MNG', 'Managua, Nicaragua'), ('PA_PAC', 'Panamá, Panamá'), ('PY_ASU', 'Asunción, Paraguay'), ('PE_LIM', 'Lima, Perú'), ('UY_MVD', 'Montevideo, Uruguay'), ('VE_CCS', 'Caracas, Venezuela')], max_length=20)),
                ('city', models.CharField(choices=[('AR_BUE', 'Buenos Aires'), ('BO_LPZ', 'La Paz'), ('BR_SPA', 'São Paulo'), ('CL_STG', 'Santiago'), ('CO_ANT', 'Medellín'), ('CO_ATL', 'Barranquilla'), ('CO_BOL', 'Cartagena de Indias'), ('CO_BOG', 'Bogotá'), ('CO_MAG', 'Santa Marta'), ('CO_VAL', 'Cali'), ('CR_SJO', 'San José'), ('CU_HAV', 'La Habana'), ('DO_SDO', 'Santo Domingo'), ('EC_PCH', 'Quito'), ('SV_SAL', 'San Salvador'), ('GT_GUA', 'Guatemala'), ('HN_FMZ', 'Tegucigalpa'), ('MX_CMX', 'Ciudad de México'), ('NI_MNG', 'Managua'), ('PA_PAC', 'Ciudad de Panamá'), ('PY_ASU', 'Asunción'), ('PE_LIM', 'Lima'), ('UY_MVD', 'Montevideo'), ('VE_CCS', 'Caracas')], max_length=50)),
                ('order_note', models.TextField(blank=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('order_status', models.CharField(choices=[('New', 'Nuevo'), ('Accepted', 'Aceptado'), ('Completed', 'Completado'), ('Cancelled', 'Cancelado')], default='P', max_length=9)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pendiente', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
    ]
